set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports buttonsin]
set_property PACKAGE_PIN W8 [get_ports {buttonsin[0]}]
set_property PACKAGE_PIN V10 [get_ports {buttonsin[1]}]
set_property PACKAGE_PIN W11 [get_ports {buttonsin[2]}]
set_property PACKAGE_PIN W12 [get_ports {buttonsin[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports buttonsout]
set_property PACKAGE_PIN AB7 [get_ports {buttonsout[0]}]
set_property PACKAGE_PIN AB6 [get_ports {buttonsout[1]}]
set_property PACKAGE_PIN Y4 [get_ports {buttonsout[2]}]
set_property PACKAGE_PIN AA4 [get_ports {buttonsout[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports S]
set_property PACKAGE_PIN Y11 [get_ports {S[0]}]
set_property PACKAGE_PIN AA11 [get_ports {S[1]}]
set_property PACKAGE_PIN Y10 [get_ports {S[2]}]
set_property PACKAGE_PIN AA9 [get_ports {S[3]}]
set_property PACKAGE_PIN AB11 [get_ports {S[4]}]
set_property PACKAGE_PIN AB10 [get_ports {S[5]}]
set_property PACKAGE_PIN AB9 [get_ports {S[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports LEDs]
set_property PACKAGE_PIN T22 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN T21 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U22 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN U21 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN V22 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN W22 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[6]}]
set_property PACKAGE_PIN U14 [get_ports {LEDs[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports signalout]
set_property PACKAGE_PIN AA8  [get_ports signalout]